<template>
  <div class="homepage">
    <div class="logo-container">
      <img class="logo" src="/img/logo/alex logo.svg" alt="logo" />
    </div>
    <div class="alex-container">
      <h2>Alexandre</h2>
    </div>
    <div class="soares-container">
      <h2>Soares</h2>
    </div>
    <div class="left">
      <div class="title slide-in-left">
        <h1>VueJS Developer</h1>
      </div>
      <img src="/img/homepage/alex-black.jpg" alt="left" />
    </div>
    <div class="right">
      <div class="title slide-in-right">
        <h1>Personal</h1>
      </div>
      <img src="/img/homepage/alex-white.jpg" alt="right" />
    </div>
  </div>
</template>

<script>
export default {}
</script>

<style lang="scss" scoped>
h1 {
  width: 100%;
  text-align: center;
  z-index: 999;
  position: absolute;
  bottom: 10%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.homepage {
  height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;

  & .left {
    background-color: #000;
    flex: 1;
    height: 100%;

    & h1 {
      color: white;
    }

    &:hover {
      flex: 1.4;
      & .title {
        display: block;
      }
    }
  }

  & .right {
    flex: 1;
    height: 100%;
    background-color: #fff;

    & h1 {
      color: black;
    }

    &:hover {
      flex: 1.4;
      & .title {
        display: block;
      }
    }
  }

  & .left,
  & .right {
    position: relative;
    cursor: pointer;
    transition: all 0.6s ease-in-out;

    & img {
      z-index: 900;
      width: 70%;
      margin: 0 auto;
      display: block;
      object-fit: cover;
    }
  }
}

.title {
  display: none;
  position: absolute;
  top: 0;
  left: 0;
  z-index: 999;
  height: 100%;
  width: 100%;
}

.logo-container {
  z-index: 9999;
  height: 10rem;
  width: 10rem;
  position: absolute;
  top: 10%;
  text-align: center;
  left: 50%;
  transform: translate(-50%, -50%);
}

.alex-container,
.soares-container {
  text-align: center;
  z-index: 9999;
  position: absolute;
  top: 10%;
  transform: translateY(-50%);

  & h2 {
    width: 25rem;
    font-weight: 400;
    color: #86171f;
    display: inline-block;
  }
}

.alex-container {
  left: 26%;
  text-align: right;

  @media only screen and (max-width: $bp-biggest) {
    left: 24%;
  }

  @media only screen and (max-width: $bp-largest) {
    left: 20%;
  }

  @media only screen and (max-width: $bp-large) {
    left: 16%;
  }

  @media only screen and (max-width: $bp-medium) {
    left: 14%;
  }
}

.soares-container {
  right: 26%;
  text-align: left;

  @media only screen and (max-width: $bp-biggest) {
    right: 24%;
  }

  @media only screen and (max-width: $bp-largest) {
    right: 20%;
  }

  @media only screen and (max-width: $bp-large) {
    right: 16%;
  }

  @media only screen and (max-width: $bp-medium) {
    right: 14%;
  }
}

.slide-in-right {
  -webkit-animation: slide-in-right 0.6s ease-in-out both;
  animation: slide-in-right 0.6s ease-in-out both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-7-27 22:27:50
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-right
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(20rem);
    transform: translateX(20rem);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(20rem);
    transform: translateX(20rem);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}

.slide-in-left {
  -webkit-animation: slide-in-left 0.6s ease-in-out both;
  animation: slide-in-left 0.6s ease-in-out both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-7-27 22:27:50
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-20rem);
    transform: translateX(-20rem);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-20rem);
    transform: translateX(-20rem);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
</style>
